import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Footer } from '@south-blog/components';
import "./globals.css";
import '../../../../shared/styles/reset.css';
import '../../../../shared/styles/index.css';
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <div>
          <Header />
          <div className='bg-[#f5f6f9]'>
            <div className='mx-[15vw] h-[1000px]'>
              { children }
            </div>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
